### ISSUE TITLE
Conflicting attributes in CML convntions

### ISSUE THREAD

**Issue by maxmargraf** [OpenSenseAction/OS_data_format_conventions#10]
We set an attribute for missing values called `missing values` which interferes with the `_FillValue` which is the name for missing values in the [cf conventions](https://cfconventions.org/cf-conventions/cf-conventions.html#missing-data). Therefore I suggest to change the attribute to `_FillValue`.

**Comment by fenclmar** [comment]
corrected by all three sensors
